String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Scugs!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Slugcat images can be found in the game files; Rain World and all its characters belong to Akupara Games and Videocult. Please buy the original game and support the creators!",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048 SLUGCATS #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'The Monk',
    '%4'                    : 'The Survivor',
    '%8'                    : 'The Watcher',
    '%16'                   : 'The Hunter',
    '%32'                   : 'The Gourmand',
    '%64'                   : 'The Rivulet',
    '%128'                  : 'The Spearmaster',
    '%256'                  : 'The Artificer',
    '%512'                  : 'The Saint',
    '%1024'                 : '???',
    '%2048'                 : 'sigmacat',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'Monk',
    '%p4'                   : 'Survivor',
    '%p8'                   : 'Watcher',
    '%p16'                  : 'Hunter',
    '%p32'                  : 'Gourmand',
    '%p64'                  : 'Rivulet',
    '%p128'                 : 'Spearmaster',
    '%p256'                 : 'Artificer',
    '%p512'                 : 'Saint',
    '%p1024'                : '???',
    '%p2048'                : 'sigmacat',
    '%p4096'                : '2017 Confetti Vanilla',
    '%p8192'                : 'Rainbow'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Scugs!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Slugcat images can be found in the game files; Rain World & all its characters belong to Akupara Games and Videocult. Please support the original creators and buy this amazing game!",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048 SLUGCATS #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'The Monk',
    '%4'                    : 'The Survivor',
    '%8'                    : 'The Watcher',
    '%16'                   : 'The Hunter',
    '%32'                   : 'The Gourmand',
    '%64'                   : 'The Rivulet',
    '%128'                  : 'The Spearmaster',
    '%256'                  : 'The Artificer',
    '%512'                  : 'The Saint',
    '%1024'                 : '???',
    '%2048'                 : 'sigmacat',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : '2017 Confetti Vanilla',
    '%p8192'                : 'Rainbow'
  }

});
